AWSTemplateFormatVersion: '2010-09-09'
Resources:
  HttpApi:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: 'S3ProxyApi'
      ProtocolType: 'HTTP'
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET

  S3Integration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: 'HTTP_PROXY'
      IntegrationUri: 'https://value-labo-test-contents-001.s3.amazonaws.com'
      PayloadFormatVersion: '1.0'
      IntegrationMethod: 'ANY'

  S3Route:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: '$default'
      Target: !Sub 'integrations/${S3Integration}'

  DefaultStage:
    Type: 'AWS::ApiGatewayV2::Stage'
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true

Outputs:
  ApiEndpoint:
    Description: 'The URL of the API Gateway HTTP API'
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
