AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  ProjectName:
    Type: String
    Default: hands-on-apigw
  BucketName:
    Type: String

Resources:
  HttpApi:
    Type: 'AWS::ApiGatewayV2::Api'
    Properties:
      Name: !Sub ${ProjectName}-ProxyApi
      ProtocolType: 'HTTP'
      CorsConfiguration:
        AllowOrigins:
          - '*'
        AllowMethods:
          - GET

  S3Integration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: 'HTTP_PROXY'
      IntegrationUri: !Sub "https://${BucketName}.s3-${AWS::Region}.amazonaws.com"
      PayloadFormatVersion: '1.0'
      IntegrationMethod: 'ANY'

  LambdaIntegration:
    Type: 'AWS::ApiGatewayV2::Integration'
    Properties:
      ApiId: !Ref HttpApi
      IntegrationType: 'AWS_PROXY'
      IntegrationUri:
        !ImportValue LambdaFunctionArn-hands-on-apigw-calc-addition
      PayloadFormatVersion: '2.0'
      TimeoutInMillis: 30000

  S3Route:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: '$default'
      Target: !Sub 'integrations/${S3Integration}'

  ApiRoute:
    Type: 'AWS::ApiGatewayV2::Route'
    Properties:
      ApiId: !Ref HttpApi
      RouteKey: GET /calc/add
      Target: !Sub integrations/${LambdaIntegration}

  DefaultStage:
    Type: 'AWS::ApiGatewayV2::Stage'
    Properties:
      ApiId: !Ref HttpApi
      StageName: '$default'
      AutoDeploy: true

  LambdaInvokePermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !ImportValue LambdaFunctionArn-hands-on-apigw-calc-addition
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${HttpApi}/$default/GET/*/*


Outputs:
  ApiEndpoint:
    Description: 'The URL of the API Gateway HTTP API'
    Value: !Sub 'https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com'
    Export:
      Name: !Join
        - '-'
        - - ApiEndpoint
          - !Ref ProjectName